- name: creating catalouge
  hosts: catalogue
  become: yes
  tasks:
  - name: Run nodejs script
    tags:
    - installation
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  - name: installing nodejs
    tags:
    - installation
    ansible.builtin.yum:
     name: nodejs
     state: present
  - name: checking user
    tags:
    - installation
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true
  - name: Add the user 'roboshop' after validating
    tags:
    - installation
    when: out.rc == 1
    ansible.builtin.user:
     name: roboshop  
  - name: checking app directory
    tags:
    - installation
    ansible.builtin.stat:
     path: /app
    register: directory
  - name: Create a directory app
    tags:
    - installation
    when: directory.stat.exists == False
    ansible.builtin.file:
     path: /app
     state: directory 
  - name: Download catalogue.zip
    tags:
    - deployment
    ansible.builtin.get_url:
     url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
     dest: /tmp 
          
  - name: extract catalogue.zip
    tags:
    - deployment
    ansible.builtin.unarchive:
     src: /tmp/catalogue.zip
     dest: /app
     remote_src: yes   
  - name: download npm
    tags:
    - deployment
    ansible.builtin.command: npm install 
    args:
     chdir: /app
  - name: copy catalogue service
    tags:
    - installation
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service   
  - name: Reload catalogue
    tags:
    - deployment
    ansible.builtin.systemd:
     daemon_reload: true  
  
  - name: Copying mongo.repo
    tags:
    - installation
    ansible.builtin.copy:
     src: mongo.repo
     dest: /etc/yum.repos.d/mongo.repo   
  - name: installing mongo-org-shell
    tags:
    - installation
    ansible.builtin.yum:
     name: mongodb-org-shell
     state: present   
  - name: loading schema
    tags:
    - installation
    ansible.builtin.shell: mongo --host 184.73.67.223 < /app/schema/catalogue.js 
  - name: Start service catalogue and enable
    tags:
    - deployment
    ansible.builtin.service:
     name: catalogue
     state: started
     enabled: true       


  
          
 




